[package]
name = "vm-translator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "VMTranslator"
path = "src/main.rs"

[dependencies]
eyre = "0.6.12"
thiserror = "1.0.59"
